### ISSUE TITLE
minor metadata bugs

### ISSUE THREAD

**Issue by hfattahi** [opera-adt/PROTEUS#13]
I noticed this [typo](https://github.com/opera-adt/PROTEUS/blob/main/src/proteus/dswx_hls.py#L575) where Sentinel-1 should change to Sentinel-2.

Also I noticed that when we open a dataset with gdal, we are not specifying that the data is open in read mode. I think by default the dataset is opened in update mode (GA_Update). Whenever we open the dataset for read only purpose, we may clarify that by specifying GA_ReadOnly. For example [this](https://github.com/opera-adt/PROTEUS/blob/main/src/proteus/dswx_hls.py#L542) may change to:

```
layer_gdal_dataset = gdal.Open(filename, gdal.GA_ReadOnly)
```

**Comment by gshiroma** [comment]
Thank you, @hfattahi . I'll update the code, but the "bug" has no effect at all. This happens because HLS Sentinel files have the attribute `PLATFORM_NAME` so, the processing of S30 products would enter in the first `if` statement [here](https://github.com/opera-adt/PROTEUS/blob/9bab5f63f6fc395064590c5749a1825b24339880/src/proteus/dswx_hls.py#L565) and will not (or should not) enter in the `else if` statement [here](https://github.com/opera-adt/PROTEUS/blob/9bab5f63f6fc395064590c5749a1825b24339880/src/proteus/dswx_hls.py#L570), that includes the path to the line of code that you pointed out.

That `else if` statement is written to HLS Landsat products that do not have the attribute `PLATFORM_NAME`. These products have the attribute `SENSOR` instead.

In spite of that, I'll update the code to fix the typo.

**Comment by gshiroma** [comment]
I'll also add `gdal.GA_ReadOnly` to `gdal.Open()` following your suggestion. Thanks!

**Comment by gshiroma** [comment]
Thank you again for opening this issue, @hfattahi . Your comments (S1/S2 typo and opening files in read mode) were fully addressed in the mid-May point release: 
https://github.com/opera-adt/PROTEUS/releases/tag/v0.3 .
